language: c
script: ./travis-tool.sh run_tests
before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - sudo apt-get install alien
install:
  - ./travis-tool.sh install_deps
  - sh -e /etc/init.d/xvfb start
notifications:
  email:
    on_success: change
    on_failure: change
env:
  - global:
    - WARNINGS_ARE_ERRORS=1
    - _R_CHECK_FORCE_SUGGESTS_=0
    - DISPLAY=:99.0
