language: c
script: ./travis-tool.sh run_tests
before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - ./travis-tool.sh r_binary_install rgl RANN igraph filehash digest testthat yaml XML RcppEigen
  - bash <(wget -q -O- http://neuro.debian.net/_files/neurodebian-travis.sh)
  - sudo apt-get install cmtk --no-install-recommends
install:
  - ./travis-tool.sh github_package jimhester/covr
  - ./travis-tool.sh install_deps
  - sh -e /etc/init.d/xvfb start
notifications:
  email:
    on_success: change
    on_failure: change
env:
  global:
    - secure: U5L4JHPa5/mpcDjL60XZVDXtT/nQe4lyhCG6pIj7dF8N6iLRO/vh0ChPxZsBhunKaNMnu59MEqn9nvp09kodV7DzW1nNV+UVi2ZtXpAFejHOK6T4d31vGShCnoM5BkTeMp7exX8yfKWw3Zw0JY47sHTLFihYbwUFqsus0aqT0hIK
    - WARNINGS_ARE_ERRORS=1
    - _R_CHECK_FORCE_SUGGESTS_=0
    - DISPLAY=:99.0
after_success:
  - Rscript -e 'library(covr);coveralls(exlusions="R/zzz.R")'
  - chmod 755 ./travisbuildchildren.sh
  - ./travisbuildchildren.sh
